CHANGELOG.md, README.md, pumps/elasticsearch.go
Rather than one static index
In ES, this enables easy backups to be taken of individual days worth of logs, and for index settings changing at midnight without having to reindex all existing data
Also removed the explicit "CreateIndex" call as by default when you insert a document into an index for the first time it creates the index in ES. Could add this back in as an option later
Branched off from develop this time? Which would you prefer I worked from / merged into?
=> RH: Added ability to put all data into a new index every day 

pumps/influx.go
The current pump for influx is failing because of some missing allocations on the maps.  As well all the strings are being decoded with quotes.  This is stripping those quotes before putting them in the db.
=> Influx DB fixes for map allocations and string trims

README.md, pumps/elasticsearch.go
Adds an "extended_stats" flag which changes the behavior of the Elasticsearch pump to include the following additional fields in the Elasticsearch payload:
* Raw Request
* Raw Response
* User Agent
Defaults to false if not specified which should ensure backward compatibility with existing users. Depending on raw request or response sizes could impact on performance which is why this has been implemented as an optional flag.
I've also added very brief compile instructions to the README to assist those in the future who are new to Go compilation!
=> Elasticsearch Extended Stats Mode

pump.example.conf
This pump is required for users to see analytics graphs in their installs so should be present as default.
=> Update pump.conf to include mongo aggregates pump

pumps/mongo.go, pumps/mongo_selective.go
MongoDB collections for analytics (both generic and selective) lack indices that make querying them (e.g. with the dashboard log browser) efficient. This adds a composite index that would work in most cases as well as by-orgid and by-apiid indices for the generic collection. It also removes the ones that don't make much sense: an orgid index for selective collections, which are already naturally per-org, composite indices that start with `_id` and thus never really utilised.
In general this would significantly increase dashboard log browser performance for large collections (multiple GB and larger), lower the load on MongoDB itself when performing related queries. At the same time removing unused indices decreases the storage requirements somewhat.
Related to #74.
=> Create better MongoDB indices for corresponding pumps

README.md, config.go, main.go
It falls back to using "key" if "type" not speicified
So backward compatible with previous configs
Now you can define multiple pumps like this:
```
"csv": {
"type": "csv",
"meta": {
"csv_dir": "./"
}
},
"csv_alt": {
"type": "csv",
"meta": {
"csv_dir": "./"
}
},
```
=> Add new "type" field which is used to determine pump type

vendor/github.com/logzio/logzio-go/LICENSE, vendor/github.com/logzio/logzio-go/README.md, vendor/github.com/logzio/logzio-go/logziosender.go, vendor/vendor.json
```
pumps/logzio.go:11:2: cannot find package "github.com/logzio/logzio-go" in any of:
/Users/ahmet/go/src/github.com/TykTechnologies/tyk-pump/vendor/github.com/logzio/logzio-go (vendor tree)
/usr/local/go/src/github.com/logzio/logzio-go (from $GOROOT)
/Users/ahmet/go/src/github.com/logzio/logzio-go (from $GOPATH)
```
=> adding logzio dependencies to vendor

utils/dist_build.sh
This allows us to use the official golang 1.12 images rather than
having to install it by hand on jessie.
rpm-sign.sh is on the BuddyFS/build_tools.
=> Signing rpms using gpg2 and the agent

analytics/aggregate.go, pumps/hybrid.go, pumps/mongo_aggregate.go
Added new field `track_all_paths` in configuration of Mongodb Aggregate and Hybrid Pump.
Also, new fields are added in collection of aggregate logs:
1. `keyendpoints`
2. `lists.keyendpoints`
3. `oauthendpoints`
4. `lists.oauthendpoints`
It will store data only for **tracked endpoints**. To store data for all endpoints, set  `track_all_paths` field to true. 
Format of data is as follows
```json
"keyendpoints/oauthendpoints":{
"keyId/oauthId":{
"Base64(APIID:Endpoint)":{
"errortotal" : 0,
"hits" : 1,
"humanidentifier" : "Base64(APIID:Endpoint)",
"identifier" : "Base64(APIID:Endpoint)",
"lasttime" : "2019-07-15T07:18:22.708Z",
"success" : 1,
"totalrequesttime" : 292.0,
"requesttime" : 292.0
}
}
}
"lists.keyendpoints/lists.oauthendpoints":{
"keyId/oauthId":[
{
"errortotal" : 0,
"hits" : 1, …
```
=> Added new fields  in aggregate collection

analytics/aggregate.go
Fixes #135 
PR #120 removed `Lists` field from `AnalyticsRecordAggregate` structure. 
Because of this lists data was not getting pushed to the mixed aggregate collection, which are used to generate the listing
=> Restore lists data in aggregate mixed collection

pumps/influx.go
Devs at our company noticed that the influx pump was SUPER slow on doing writes when you have larger amounts of data.  Digging in a bit we've located a small bug that causes a big problem.  In the `WriteData` function the incoming records are processed to send out to influx, but instead of waiting until all records have been processed and then sending a write, the `Write` got accidentally put inside the loop.
Say you have 5000 records incoming in a purge loop, that would end up sending 5000 separate POSTS to influx.  The first post would have 1 record, the second would have 2, etc.  After fixing this the influx writes got very fast.
=> Fix influx pump write loop duplication

README.md, pump.example.conf
As `name` has been deprecated, have changed all mentions to `type`.
=> Change name to type in sample and readme

pumps/elasticsearch.go
This PR is for publishing the alias into the Elasticsearch. We can use the alias for different purposes such as identifying the users in the analytics.
[Github issue](https://github.com/TykTechnologies/tyk-pump/issues/38) and [community forum ](https://community.tyk.io/t/user-identifier-in-analytic-logs/1621/3) are described this issue.
=> Fixed in Elasticsearch analytics to publish the alias

pumps/mongo_aggregate.go
This changes log in mongo aggregate pump to use Debug.
It is unnecessary noisy with debug information
=> Reduce log noises from mongo aggregate pump

analytics/aggregate.go, analytics/analytics.go
Fixes #151 
1. **latency.upstream**: Records latency caused by the upstream
2. **latency.total**: Records total end-to-end latency
1. **max_upstream_latency**: Records maximum upstream latency
2. **min_upstream_latency**: Records minimum upstream latency
3. **total_upstream_latency**: Records total upstream latency
4. **max_latency**: Records maximum end-to-end latency
5. **min_latency**: Records minimum end-to-end latency
6. **total_latency**: Records total end-to-end latency
7. **latency**: Avg latency
8. **upstream_latency**: Avg upstream latency
=> Store latency information

storage/redis.go
Fixes #159
The logs now looks like
```
[Oct 18 09:50:40] DEBUG redis: Analytics returned: 2
[Oct 18 09:50:40] DEBUG redis: Unpacked vals: 0
```
=> log only length of records from redis

analytics/aggregate.go, pumps/hybrid.go, pumps/mongo_aggregate.go
Fixes #162 
Added additional config options:
1. `ignore_tag_prefix_list`( in mongo aggregate and hybrid pump.)
It will not store analytics for tags having prefix specified in the list.
**Note**: Prefix `key-` is added in the list by default. This tag is added by gateway for keys.
2. `threshold_len_tag_list`( in mongo aggregate pump)
If number of tags in a document grows beyond `threshold_len_tag_list`, pump will throw a warning. The warning will print top 5 common tag prefix. Default value is **1000**. To disable alerts set it to -1.
=> Add config option to ignore tags with common prefix

analytics/aggregate.go, pumps/hybrid.go, pumps/mongo_aggregate.go
Fixes #164 
Added `store_analytics_per_minute` config option in aggregate and hybrid pumps.
Currently, we generate aggregate data per hour. If this option is enabled, aggregate data will be generated per minute.
=> Option to store analytics per minute

analytics/aggregate.go
Fixes #113 
MongoDB doesn't support `.` in parent field names.[[1](https://docs.mongodb.com/v3.4/reference/limits/#Restrictions-on-Field-Names)]
If an endpoint path contained `.` , mongoDB data was corrupted.
To fix this, `.` char will be replaced with it's unicode representation.
=> Handle unsupported MongoDB characters

pumps/elasticsearch.go
The underline client already supports having multiple URLs, our job is just to provide it.
At the moment implementation rely on "," separator.
=> Add support for multiple ES urls

main.go, pumps/mongo.go
currently the timeout is infinite, and there is no logs.  this is a poor user experience
this improves uptime pump by adding more logs and removing the infinite loop.
fixes https://github.com/TykTechnologies/tyk-pump/issues/117
=> improve uptime pump by adding more logs and removing the infinite loop

pumps/elasticsearch.go
Allows decoding base64 raw request/response data.
=> Extend ES pump with `decode_base64` boolean option

storage/redis.go
This PR: 
- deprecates `hosts` config parameter, adds `addrs ` instead.
- changes client definition logic. If `enable_cluster` is `true`, client is run in cluster mode, otherwise, it is run in single node mode.
Fixes #190
=> Change redis client logic

pumps/mgo_helper_test.go, pumps/mongo.go, pumps/mongo_aggregate.go, pumps/mongo_selective.go
Since AWS DocumentDB runs with TLS enabled, so it required a way to run it without disabling TLS verification.
DocumentDB use self-signed certs for verification, and provide a bundle with root certificates for verification, so we need a way to load this bundle.
Additionally DocumentDB can't be exposed to the local machine outside of VPC, which meant that even if verification is turned on, it will always fail since if we use ssh tunnel or similar, domain will differ from original.
Plus we may need a way to enable mutual TLS support.
Added the following options (on pump level):
- `mongo_ssl_ca_file` - path to the PEM file with trusted root certificates
- `mongo_ssl_pem_keyfile` - path to the PEM file which contains both client certificate and private key. Required for MutualTLS.
- …
=> Add support for AWS DocumentDB

pumps/mongo.go, pumps/mongo_aggregate.go, pumps/mongo_selective.go
Helps with feedback regarding issue #92.
- it is possible to specify settings for Mongo connections via
environment variables that are prefixed appropriately
- these log changes will show the dial info used by the Mongo connection
attempt so that any pertinent config changes can be seen, to aid
troubleshooting
- if the 'password' or other similarly sensitive fields on the dial info
struct were populated, they would show up in the error logs
For example, launching the pump with `PMP_MONGO_MONGOURL` set to `unavailable_url` would result in Mongo reporting the connection failure and (as a result of this change) including the bad URL in the error log, like so:
```
[Mar  4 10:09:57] ERROR mongo-pump: Mongo connection failed. Retrying. dialinfo=&{Addrs:[unavailable_url] ...
```
=> Add dial info to Mongo connection error logs.

pumps/mongo.go, pumps/mongo_selective.go
It is a working situation, we just changed index name, but it is content the same.
Fix https://github.com/TykTechnologies/tyk-pump/issues/234
=> Ignore index "exists" error

README.md
Per this doc https://tyk.io/docs/tyk-configuration-reference/tyk-pump-configuration/tyk-pump-configuration/#configuration
=> fixed to "use_ssl" for Kafka per doc in tyk.io/doc

server/server.go
Fix healthCheck to be accessible from outside of the server. Currently is only accessible from localhost
fixes #266
Be able to check health of application from outside with monitoring tools.
Locally test with
http://localhost:8080/health
http://10.160.255.103:8080/health
=> Fix health endpoint to be published outside server.

README.md, analytics/analytics_filters.go, analytics/analytics_filters_test.go
Add new filters based on response_code's
Currently we have the necessity to be able to only send with pump request with errors. For that we need to implement this new filter to be able to remove all 200 response code.
Decrease space required to store all data of analytics . Request with 200 are not important to be monitorized and also are the 99% of traffic. We have some problems regarding sizing of our cluster of kafka and we want to reduce the load.
-Unit test
-Start pump in local with same config of our staging environment with the new filter.
=> Add new filters based on response_code's

README.md
missing comma at kafka section in demo config.
=> fix: missing comma in kafka config

pumps/elasticsearch.go
Fixing base64 decoding for ElasticSearch
Fixing the base64 decoding for ElasticSearch raw request and response.
Issue #52 
The config option `decode_base64` for ElasticSearch wasn't working.
Tested with `decode_base64` true and false. It works ok. 
Analytic record with `decode_base64`false:
Analytic record with `decode_base64`true:
- [] My change requires a change to the documentation.
=> [TN-6] Fix base64 ES decoding

pumps/splunk.go
Splunk pump now has `obfuscate_api_keys` option
=> Add option to obfuscate keys when writing to splunk

pumps/syslog.go
Ticket #269 introduced a change in the main pump data structure, this fix is required in order to prepare a build that incorporates both #269 and #189.
=> Fix omit_detailed_recording on syslog pump

pumps/mongo.go, pumps/mongo_aggregate.go, pumps/mongo_selective.go
The url set in the logs for the mongo Pump now contains the sensitive data blurred.
https://tyktech.atlassian.net/browse/TT-556
https://github.com/TykTechnologies/tyk-pump/issues/282
Give solution to https://tyktech.atlassian.net/browse/TT-556
- Configure Pump file to use mongo
- Ran tyk-pump and check the logs
- The regex was also tested in https://regex101.com/r/E34wQO/1
=> TT-556 blurred the sensitive data in mongo logs

main.go, pumps/mongo.go, pumps/mongo_aggregate.go, pumps/mongo_selective.go
The idea behind this PR is to make mongo pumps (mongo, mongo-aggregate, and mongo-selective) timeout configurable.
To do that, we modify the `dialInfo` in the connect method, since when we do a `mgo.DialWithInfo` to get the session, [the library sets](https://github.com/go-mgo/mgo/blob/a6b53ec6cb22a3699387a57a161566f9402ee85b/session.go#L426) the [SyncTimeout](https://godoc.org/gopkg.in/mgo.v2#Session.SetSyncTimeout) and [SocketTimeout](https://godoc.org/gopkg.in/mgo.v2#Session.SetSocketTimeout) and each time we try to write, we copy that session (the timeouts are re-initialized).
Also added a goroutine control in the mongo pump, since before it was spamming goroutines and don't do anything with the result (if it has an error or something).
https://tyktech.atlassian.net/browse/TT-695 …
=> [TT-695] Mongo pumps Timeout

.gitignore, README.md, pumps/dogstatsd.go
There is no option to customize DogStatsD and this may have a negative impact on the billing with tags like `path` that are sent by default.
This PR adds an option to configure the tags pushed to DogStatsD.
Decrease the cost of Datadog.
There are no automated tests for the `dogstatsd.go` file. I did some manual tests and the code works.
=> Update DogStatsD to support customizable tags

README.md, analytics/analytics.go, analytics/analytics_test.go, config.go, main.go, main_test.go
While filtering the record I thought it's good timing to obfuscate the key. For every record, I check if it needs to be filtered out and then obfuscate the key.
There's a global config field to turn this on - obfuscate_keys
Added TestObfuscateKeys just for that obfuscation function.
Added tests for filter+obfuscation of keys in a record
~Important: This PR is only useful if keys are not hashed, otherwise there's no real reason to obfuscate the key but it works for both cases.~
About hashed keys (that is set in the GW):
- In the case of detailed recording, it doesn't matter since we record the request as-is, and as such, you can see the authorization header in the raw request.
- If there is no detailed recording set, then APIKey field in the analytic record has the key so customers that …
=>  Add capability to obfuscate keys for all records

config.go, main.go
This PR adds support for multiple analytic keys and is backward compatible with the old analytic key (`tyk-system-analytic`).
It just basically do the following process:
Iterate from -1 to 9:
- If the iteration is -1 (the first one), we're going to look for the old analytic key (`tyk-system-analytic`)
- If the iteration is from 0 to 9, we're going to look for the new divided key (`tyk-system-analytic_X` where X is the iteration number)
- Read from the Redis the key 
- Process data
- Jump to the next key
This allows us to:
- Loss fewer analytics records if a pump fails since it will only lose the records from one of the keys.
- If the Redis cluster is enabled, read the analytics across multiple nodes. 
https://tyktech.atlassian.net/browse/TT-1574
Reduce redis overload and have a better …
=> [TT-1574] Multiple analytics keys

pumps/sql_aggregate.go, pumps/sql_aggregate_test.go
This PR implements table sharding in `SQLAggregatePump`. The logic is a bit different when you compare with other pumps' table sharding. This PR handles everything within one for loop. Also, it doesn't make auto migration separately for the first and second days, instead, it make migration when it is necessary.
=> [TT-2783] Implement table sharding for SQLAggregatePump

main.go
When the max record size for pump is set, then we should trim
https://tyktech.atlassian.net/browse/TT-1032
fix https://tyktech.atlassian.net/browse/TT-1032
- Set max record size in general
- check correct trimming
- Set max record size per pump
- check correct trimimg
=> TT-1032 consider max record for pump when trimming

pumps/kafka.go
Add tags to the Kafka Pump
Currently, Access logs from Tyk are published to Kafka without tags. On contrary, in the ElasticSearch they are published.
We need this change in our project that uses Tyk and Tyk Pump.
=> publish tags in the kafka pump

.github/workflows/release.yml
Unblock push to package cloud by updating github action step, m4 template PR is on the way, but blocked by a change to request, lets fix this now.
=> Update package cloud github action

pumps/prometheus.go, pumps/prometheus_test.go
Basically, the for loop always took the last memory address of the custom metrics config. That makes the custom metrics always take the last custom metric value. 
Needs to add unit tests before merging.
https://tyktech.atlassian.net/browse/TT-6343
Added unit tests - tested manually
=> TT-6343 Fixing mem address pointer in prom custom metrics

analytics/aggregate.go, analytics/aggregate_test.go, analytics/analytics.go, analytics/analytics_test.go, pumps/hybrid.go, pumps/mongo.go, pumps/mongo_aggregate.go, pumps/mongo_test.go, pumps/sql_aggregate.go
This PR adds the behavior of ignoring graph analytics records. This means that records that carry the tag `tyk-graph-analytics` won't be stored in the `tyk-analytics` and `tyk_analytics_aggregate` collection (if using default names).
It's a non-breaking change and the new pump to handle graph analytics will be following shortly.
*Why this change?*
Graph records are different from classic REST records. Instead of endpoints graphs are dealing with operations and operation paths. 
HTTP status codes are less relevant for errors, instead, the errors are part of the body response.
All that means that a different struct is necessary to store this data - so we don't need to store graph data in the current collections.
[TT-6121](https://tyktech.atlassian.net/browse/TT-6121)
=> ignore graph analytics for mongo pump(s)

pumps/prometheus.go, pumps/prometheus_test.go
Added a function to force `type` to be set when the metric is an histogram
TT-6482
Do not panic when someone configures an histogram without the label `type`
- Ran Pump with the config:
```
{
"analytics_storage_type": "redis",
"analytics_storage_config": {
"type": "redis",
"host": "tyk-redis",
"port": 6379,
"hosts": null,
"username": "",
"password": "",
"database": 0,
"optimisation_max_idle": 100,
"optimisation_max_active": 0,
"enable_cluster": false
},
"purge_delay": 2,
"pumps": {
"prometheus": {
"type": "prometheus",
"meta": {
"listen_address": "localhost:9090",
"path": "/metrics",
"custom_metrics":[
{
"name":"tyk_http_latency",
"description":"Latency of API requests",
"metric_type":"histogram",
"labels":["response_code","api_name","method","api_key","alias","path"]
}
]
}
}
}, …
```
=> TT-6482 Histogram type label validation

pumps/mongo.go, pumps/mongo_aggregate.go, pumps/mongo_aggregate_test.go, pumps/mongo_selective.go, pumps/mongo_selective_test.go, pumps/mongo_test.go
We're now allowing users to choose the session consistency of their Mongo Pumps (Mongo, Mongo Selective, and Mongo Aggregate).
https://tyktech.atlassian.net/browse/TT-2485?atlOrigin=eyJpIjoiYWJlZjY4ODBjZTY1NDg1ZmIyZGNiYWM5ZTQ4OTk1NTEiLCJwIjoiaiJ9
Users can now determine the replica set focus in the Mongo Cluster. 
They can now choose between:
- `Strong` Default mode. All operations read from the current replica set primary.
- `Monotonic`
- Before the first write: Read from one of the nearest secondaries if available. Read from primary otherwise.
- After the first write: same as `strong`.
- `Eventual` Read from one of the nearest members, irrespective of it being primary or secondary. It may change servers between reads.
More info about Mongo's Read Preference …
=> [TT-2485] Support MongoDB Connection argument "readPreference"

pumps/version.go
using proper semantic for pump version (#537)
=> Merging to release-1.7: using proper semantic for pump version (#537)

go.mod, logger/init.go, logger/init_test.go
1. x-cray is being removed as an indirect gateway dependency, addressing build issues,
2. DisableColor config change removes CVE (TT-4785),
3. moved log.Level modification into init (fixes race condition in GetLogger)
https://tyktech.atlassian.net/browse/TT-7961
=> [TT-7961] Remove logrus-prefixed-formatter

go.mod, go.sum, pumps/mongo_aggregate.go, pumps/mongo_selective.go, pumps/mongo_selective_test.go
[TT-8793] Fixing Pump 1.8 bugs (#616)
* writing records to the right collection
* writing to the right collection when pump is mixed
* updating to storage 1.0.2
=> Merging to release-1.8: [TT-8793] Fixing Pump 1.8 bugs (#616)

pumps/mongo.go, pumps/mongo_aggregate.go, pumps/mongo_aggregate_test.go, pumps/mongo_selective.go, pumps/mongo_selective_test.go, pumps/mongo_test.go
TT-8905 changed the default mongo driver to mgo (#632)
* changed the default mongo driver to mgo
* change log msg to point mgo
=> Merging to release-1.8: TT-8905 changed the default mongo driver to mgo (#632)

pumps/mongo.go, pumps/mongo_test.go
[TT-8884]: added write data test for mongo pump and remove constraint (#645)
* added write data test for mongo pump and remove constraint
Added a test to cover the write data function of the mongo pump, and
removed a bug where he mongo pump only recorded graph records
* run fmt
=> Merging to release-1.8: [TT-8884]: added write data test for mongo pump and remove constraint (#645)

config.go, config_test.go
[TT-8999] Overriding pumps with the same name (#648)
* overriding pumps with the same name
* linting
* adding more test cases
* moving unit test function to the top of the file
* separating overriding test
=> Merging to release-1.8: [TT-8999] Overriding pumps with the same name (#648)

config.go, config_test.go
[TT-9126] Fix error log when omit_configfile option is enabled (#654)
* loading config file only if we shouldn't omit it
* fixing flaky test
* linting
* removing cfg.OmitConfigFile check
=> Merging to release-1.8: [TT-9126] Fix error log when omit_configfile option is enabled (#654)

pumps/mongo.go, pumps/mongo_test.go
Updated the regex in charge of matching the mongo connection strings, so it receives in the srv format and the blurred is done in the user:pass section
https://tyktech.atlassian.net/browse/TT-9228
- Added unit test
- Validated against regex validator
=> TT-9228 update regex to blur mongo credentials

.github/workflows/linter.yaml
Fix GithubActions , removed 1.18 from CI pipeline since pump uses 1.19, uses the following fixes
https://github.com/TykTechnologies/github-actions/pull/12
https://github.com/TykTechnologies/github-actions/pull/13
=> Fix pump CI

.github/workflows/linter.yaml
Fix pump CI (#695)
* removing go 1.18 from CI
* trying test-params gha branch
* trying gha improvements
* using main branch on workflows
=> Merging to release-1.8: Fix pump CI (#695)

pumps/prometheus.go, pumps/prometheus_test.go
This PR change fixes the tracking path behavior of Prometheus pump. It was tracking all the paths by default, ignoring if the API/analytic record has TrackPath enabled.
Now, when you don't have TrackPath enabled ( aka you are using Track Endpoint plugin), it will log the path as `unknown`. 
This also adds a new configuration for prometheus pump `track_all_paths` - that enables the path tracking for ALL the APIs (similar to Mongo/SQL aggregate pumps) - but  this can cause Tyk Pump malfunctioning and OOM.
https://tyktech.atlassian.net/browse/TT-9873
https://tyktech.atlassian.net/browse/TT-9873
Added tests
=> TT-9873 Fix prometheus tracking path

.github/workflows/release.yml
We need to keep master CI image uploaded to the AWS registry. Given the unability to setup a flexible policy for registry cleanup we need to refresh images.
=> run release every monday

README.md, http-retry/http-retry.go, pumps/splunk.go, pumps/splunk_test.go
TT-10564 Splunk backoff retry (#758)
* splunk backoff retry mechanism to reduce chance of losing logs
* only retry for temporary errors
* move to separate pkg outside of pumps
* set correct collector url
* ensure connection can be reused by reading and closing body stream
* reset req body to fix error when req body has already been read from previous failed request
* tidy up, change retry log to warning as not yet error
* add debugging for body bytes sent to splunk & RTT to aid in fine tuning batch size
* PR requested changes
* fix go linter issue
* applying suggested changes
* linting
---------
Co-authored-by: dominicriordan <d.riordan@sensysgatso.com>
Co-authored-by: domsolutions <56842273+domsolutions@users.noreply.github.com>
=> Merging to release-1.8: TT-10564 Splunk backoff retry (#758)

.github/workflows/ci-test.yml, .github/workflows/linter.yaml, .github/workflows/release.yml, .golangci.yaml, go.mod, main_test.go, repo-policy/main.tf
[TT-10673] Upgrading to Go 1.21 (#766)
* upgrading to Go 1.21
* fixing loop issue
* removing comment
* linting
* add release 1.19 revert 1.18 req tests
* removing commented linters
* removing 1.19 branch from terraform
---------
Co-authored-by: Esteban Ricardo Mirizio <ermirizio@gmail.com>
[TT-10673]: https://tyktech.atlassian.net/browse/TT-10673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Merging to release-1.9: [TT-10673] Upgrading to Go 1.21 (#766)

go.mod, go.sum, pumps/resurface.go, pumps/resurface_test.go
TT-10676 Upgrade Resurface Pump backend (#773)
* feat(resurface): upgrade ResurfacePump backend
* fix(resurface): flush messages before checks
* feat(resurface): upgrade ResurfacePump backend
* linting
* improving context handling
* linting
---------
Co-authored-by: Ramón Márquez <ramon.marquez@graylog.com>
=> Merging to release-1.9: TT-10676 Upgrade Resurface Pump backend (#773)

README.md, pumps/mgo_helper_test.go, pumps/mongo.go, pumps/mongo_aggregate.go, pumps/mongo_aggregate_test.go, pumps/mongo_selective.go, pumps/mongo_selective_test.go, pumps/mongo_test.go
Tyk v3/v4 does not work with MongoDB v5. Before Mongo DB 4.4 will get EOL by Feb 2024, so we are updating our default MongoDB driver to mongo-go from Tyk 5.3.
https://tyktech.atlassian.net/browse/TT-10409?atlOrigin=eyJpIjoiODdjODE2MTc4M2M1NGRiNmJkZWFhYmNjM2NlMjE1OWUiLCJwIjoiaiJ9
=> [TT-10409] Updating default Mongo driver to mongo-go

README.md
Fix typo in SQS Pump section, it says "Timestream" instead of "SQS".
=> Fix typo in SQS Pump section

README.md, pumps/sqs.go
When using AWS temporary credentials, a session token is required, so we added this new field within the SQS Pump.
https://tyktech.atlassian.net/browse/TT-10675?atlOrigin=eyJpIjoiYjI4NTIyNzhiOWJiNGYwODhmNTc0ZDBlNDYzN2Q4YzgiLCJwIjoiaiJ9
=> [TT-10675] Adding AWSToken field for temporary credentials

README.md, pumps/sqs.go
Adding AWSToken field for temporary credentials (#790)
=> Merging to release-1.9: Adding AWSToken field for temporary credentials (#790)

pumps/graph_mongo.go, pumps/graph_sql_aggregate.go
fix bug where some graphql pumps are not reading env properly (#780)
=> Merging to release-1.9: fix bug where some graphql pumps are not reading env properly (#780)

.github/workflows/release.yml
Learning from the application:
Applying templates across all branches and repos runs up against the usage limits. Larger runners are available for Team plans. This needs to be explored.
A local run of release.yml is needed to test updates before pushing it to all repos and waiting for >30mins to find out if it works.
For regular updates which collect disparate code changes, the git commit log in the repos should reflect a summary of changes that went into it.
=> [SYSE-336 master] Followup from March template application

.github/workflows/release.yml
Tyk-ci fetch mechanism needs to be fixed in order to fetch the .tgz built file from the tyk-ci release process instead of the entire repository contents
=> [SYSE-353 master] Fix tyk-ci fetch mechanism

Makefile, ci/Dockerfile.distroless, ci/goreleaser/goreleaser.yml
Removing FIPS from NFPMS (#833)
* chore: Update Dockerfile.std for fips-linux build
* feat: Update binary name for fips-linux build to tyk-pump-fips
* feat: Update binary name for fips-linux build to tyk-pump-fips
* Update binary name for fips-linux build to tyk-pump-fips
* Update Dockerfile.std and build configuration for fips-linux build
* Update Dockerfile.std and build configuration for fips-linux build
* Update Dockerfile.std and build configuration for fips-linux build
* removing duplicated jobs
* Update Dockerfile.std and build configuration for fips-linux build
* Update Dockerfile.distroless for standard package installation
* Update Dockerfile.distroless for standard package installation
* Update Dockerfile.distroless for standard package installation
* Update …
=> Merging to release-1.10: Removing FIPS from NFPMS (#833)

.github/workflows/ci-test.yml, Dockerfile
CIs are failing because version 2 was deprecated.
=> Upgrading upload-artifact to v3

.github/workflows/ci-test.yml, Dockerfile
Upgrading upload-artifact to v3 (#854)
=> Merging to release-1.11: Upgrading upload-artifact to v3 (#854)

pumps/sql.go, pumps/sql_test.go
TT-12780 prevent sql pump to panic when sharding enabled and skip api id is set (#860)
* prevent sql pump to panic when sharding enabled and skip api id is set
* revert doc change
---------
Co-authored-by: sredny buitrago <sredny@srednys-MacBook-Pro.local>
=> Merging to release-1.11: TT-12780 prevent sql pump to panic when sharding enabled and skip api id is set (#860)

analytics/analytics.go, pumps/sql.go, pumps/sql_aggregate.go, pumps/sql_aggregate_test.go, pumps/sql_test.go
=> TT-13421 create indexes on sharded sql pumps

pumps/prometheus.go, pumps/prometheus_test.go
Duplicate of #865 
Parameters for api_key obfuscation are added to the Prometheus pump.
- Adding 2 parameters in the Prometheus custom metrics in which the user can select if they want to obfuscate the API key and if yes, how many characters they want to show in it.
- Adding a validation in the `GetLabelsValues` function of the promethus pump that will validate if the variables are set and it will modify the api_key and the key parameters.
https://tyktech.atlassian.net/jira/software/c/projects/TT/boards/42?selectedIssue=TT-13937
- In my case the /metrics endpoint that is exposed by the container can be accessed by other user. We need to obfuscate the key so that we can reduce the chance of a key being leaked.
- Tested on a remote env using applications that are making constant requests to …
=> [TT-13937] Adding key obfuscation to the Prometheus pump

.github/workflows/release.yml, ci/Dockerfile.std, ci/goreleaser/goreleaser.yml
Auto generated changes by gromit to add fips compliant docker images to releases. These changes are in response to a customer request for fips compliant docker images. These are provided by using our existing fips binaries in a distroless image. THESE ARE NOT FIPS VALIDATED IMAGES. [see this ticket](https://tyktech.atlassian.net/browse/TT-15334). Changes to FIPS documentation may be required.
[Jira ticket TT-15334](https://tyktech.atlassian.net/browse/TT-15334)
There are also PRs with the same branch name on the following repos [tyk](https://github.com/TykTechnologies/tyk/tree/TT-15334/docker-fips) [tyk-sink](https://github.com/TykTechnologies/tyk-sink/tree/TT-15334/docker-fips) [tyk-analytics](https://github.com/TykTechnologies/tyk-analytics/tree/TT-15334/docker-fips)
These images were …
=> Add docker images built using FIPS binaries
