TykTechnologies/tyk-pump

- pumps/init.go
- pumps/pump.go
- pumps/segment.go
- pumps/segment_test.go
> Add segment analytics pump

- pumps/elasticsearch.go
By default, added a lot of unneeded files (ES can split out the timestamp into day/month/year so no point including them)
Also didn't use the 
> @timestamp
field name for the TimeStamp field, so the entries weren't shown in Kibana.
This standardises the output to ES
(Sorry for the diff - started using an editor which autocorrects whitespace..)
> RH: Add custom mapping for Elasticsearch output 

- pumps/elasticsearch.go
Sorry - got it slightly wrong before, but added a missed field and updated the keys for a couple of the fields.
> Some changes to how fields are mapped for Elasticsearch output

- pumps/graylog.go
I was found the wrong logic in graylogs, we have catched wrong data for raw response.
Please take a look.
> Fix wrong data of rawResponse

- pumps/mongo.go
- pumps/mongo_aggregate.go
- pumps/mongo_selective.go
> Add Mongo SSL support

- main.go
The loop needs to run forever. Do that in an actual loop instead of
using recursive tail calls. That will surely lead to a growing call
stack, eventually leading to runtime panics.
Fixes #27.
> Get rid of the infinite recursive tail call in StartPurgeLoop

- pumps/elasticsearch.go
- pumps/influx.go
- pumps/mongo_aggregate.go
- pumps/mongo_selective.go
- pumps/segment_test.go
- pumps/statsd.go
> bug: ensures sleeps for 5 seconds

- .travis.yml
- logger/init.go
- pump.example.conf
- pumps/mgo_helper_test.go
- pumps/mongo.go
- pumps/mongo_selective.go
- pumps/mongo_test.go
> configurable mongo analytics collection capacity

- pumps/init.go
- pumps/pump.go
- pumps/splunk.go
- pumps/splunk_test.go
> Splunk pump

- pumps/splunk.go
- pumps/splunk_test.go
> Splunk: add support for certificates

- config.go
- main.go
- pumps/mongo.go
> allow uptime pump to be configured via env var

- pumps/statsd.go
* Extra debug logs for connection attempts to statsD
* Removed recursion in connect function
* Check length of data > 0 before attempting connection to statsD
> lint: logging, recursion, unnecessary connects

- storage/redis.go
- vendor/github.com/TykTechnologies/redigocluster/rediscluster/rediscluster.go
- vendor/github.com/TykTechnologies/redigocluster/rediscluster/redishandle.go
- vendor/github.com/gomodule/redigo/LICENSE
- vendor/github.com/gomodule/redigo/redis/commandinfo.go
- vendor/github.com/gomodule/redigo/redis/conn.go
- vendor/github.com/gomodule/redigo/redis/doc.go
- vendor/github.com/gomodule/redigo/redis/go16.go
- vendor/github.com/gomodule/redigo/redis/go17.go
- vendor/github.com/gomodule/redigo/redis/go18.go
- vendor/github.com/gomodule/redigo/redis/log.go
- vendor/github.com/gomodule/redigo/redis/pool.go
- vendor/github.com/gomodule/redigo/redis/pool17.go
- vendor/github.com/gomodule/redigo/redis/pubsub.go
- vendor/github.com/gomodule/redigo/redis/redis.go
- vendor/github.com/gomodule/redigo/redis/reply.go
- vendor/github.com/gomodule/redigo/redis/scan.go
- vendor/github.com/gomodule/redigo/redis/script.go
- vendor/vendor.json
Added new "storage.timeout" option
Fix https://github.com/TykTechnologies/tyk/issues/2165
> Added support for redis timeouts

- analytics/analytics.go
Related to https://github.com/TykTechnologies/tyk/pull/2190
> Add Host field to AnalyticsRecord

- analytics/aggregate.go
- pumps/hybrid.go
- pumps/mongo_aggregate.go
added changes for https://github.com/TykTechnologies/tyk-pump/issues/105
- new method `PurgeAnalyticsDataAggregated` is called if `"aggregated" true` is specified in pump config
- moved aggregate logic to `tyk-pump/analytics` package
> aggregate logic moved to package, call PurgeAnalyticsDataAggregated added

- analytics/aggregate.go
Include status code 400 while calculating aggregate data for errors
> Fix aggregate data for errors.

- pumps/pump.go
- pumps/pump_test.go
This contribution is related to Issue# 126, that we were facing whenever we saw failure to connect to a source while creating a pump. Please have a look on the changes.
> Issue #126: Enhance the log in case pump not found or connected

- README.md
Update README.md for prometheus config when run as docker image
https://github.com/TykTechnologies/tyk-pump/issues/127
> Update README.md for prometheus config

- main.go
- storage/redis.go
Related to TykTechnologies/product#42
> Save pump version in redis

- analytics/aggregate.go
- analytics/analytics.go
- main.go
- pumps/mongo.go
Fix https://github.com/TykTechnologies/tyk-analytics-ui/issues/1475
> network analytics 

- install/inits/systemd/system/tyk-pump.service
> Wait for network before starting

- analytics/aggregate.go
Fixes #155
Add `$min` field in bson.M, only if it not there already
> Fix issue of min latency fields

- utils/dist_push.sh
precise was EOL a couple of years ago
bionic is the newest LTS
> Update distro releases

- pumps/elasticsearch.go
Added new `generate_id` config option
> Add a way to generate ES id

- pumps/elasticsearch.go
This PR permit to add these fields for elasticsearch : RawPath, ContentLength and Tags.
> Add RawPath, ContentLength and Tags to mapping

- pumps/mongo.go
Fixes https://github.com/TykTechnologies/tyk-pump/issues/154
> Calculate document size correctly and don't skip to write some useful data

- pumps/mongo_aggregate.go
> Fixed typo in alert message

- analytics/aggregate.go
> Aggregate pump: Handled case of zero value for Hits field of analytics record

- storage/redis.go
This PR adds Redis Sentinel client option enabled by if `master_name` isn't empty.
Regarding TykTechnologies/tyk#2769
> Add RedisSentinel client option enabled by master_name parameter

- pumps/kafka.go
Added new parameters to Kafka config:
- `use_ssl`
- `ssl_insecure_skip_verify`
Fixes #194
> Add SSL option for Kafka connection

- README.md
Documentation for https://github.com/TykTechnologies/tyk-pump/pull/201
> Add documentation for Kafka-SSL configuration

- storage/redis.go
- storage/redis_test.go
Related to https://github.com/TykTechnologies/tyk/issues/2769
> Fix sentinel configuration issues

- analytics/demo/demo.go
- main.go
Example:
./tyk-pump -c ./pump.conf --demo 12312312 --demo-api asdasdas --demo-api-version Default
> Add a way to generate fake analytics for specific API and version

- analytics/aggregate.go
Added new fields in Counter:
1. **ErrorMap**:
It stores count of occurrence for each error code in a map. 
2. **ErrorList**
It records same data as ErrorMap but stores it in a array of Document
> Record data for errorcode

- analytics/demo/demo.go
- config.go
- main.go
- pumps/csv.go
- pumps/dogstatsd.go
- pumps/dummy.go
- pumps/elasticsearch.go
- pumps/graylog.go
- pumps/hybrid.go
- pumps/influx.go
- pumps/kafka.go
- pumps/logzio.go
- pumps/moesif.go
- pumps/mongo.go
- pumps/mongo_aggregate.go
- pumps/mongo_selective.go
- pumps/mongo_test.go
- pumps/prometheus.go
- pumps/pump.go
- pumps/segment.go
- pumps/segment_test.go
- pumps/splunk.go
- pumps/splunk_test.go
- pumps/statsd.go
Needs documentation. Tests are being worked in another branch.
The idea is to solve [issue 185 ](https://github.com/TykTechnologies/tyk-pump/issues/185) improving the backpressure resilience of pump.
> Concurrent pump writing + configurable timeouts

- pumps/mongo.go
Fix Uptime Test storage casting. 
Issue #207
> Fix Uptime Test

- version.go
> Version Update

- pumps/mongo.go
- pumps/mongo_aggregate.go
- pumps/mongo_selective.go
Fix https://github.com/TykTechnologies/tyk-pump/issues/224
> Fix reading config for mongo pumps

- config.go
- pumps/mongo.go
Fix https://github.com/TykTechnologies/tyk-pump/issues/224
> Fix uptime pump config reader

- install/inits/systemd/system/tyk-pump.service
- utils/dist_build.sh
Please merge to master and all release branches.
> New signing key

- pumps/mongo.go
Fixes https://github.com/TykTechnologies/tyk-pump/issues/231
> Refactor mongo init log

- analytics/aggregate.go
Fixes #214 
Added new field `apiendpoints` in mongo aggregate document.
It stores analytics for API endpoints. The key generated to store analytics for an endpoint is hexEncode(APIID:Version:Path)
Advantage of using this key is we can fetch analytics for both API and API+version using same field.
**Note**: It records data for an endpoint only if it's tracked
Dashboard part https://github.com/TykTechnologies/tyk-analytics/pull/1716
> Store analytics for popular endpoints

- README.md
The HTTP scheme needs to be provided, otherwise this will generate an error. It makes sense to add to our example in the readme otherwise people will make this mistake.
> Added http for ES connection string

- pumps/hybrid.go
The idea of this PR is to add an RPC connection validation on each Hybrid pump write and a reconnection mechanism.
Closes #264 .
Solves the problem that happens when the RPC connection is lost (network issues / idle connection) and the hybrid pump doesn't try to reconnect again. 
- Run hybrid pump
- Wait for 24hrs+ without writing any record OR disconnect the machine network.
- Write an analytic record.
It should show you `ERROR hybrid-pump: Failed to login to RPC server, trying to reconnect...` and automatically reconnect, the next record you write it should be written fine.
> [TN-9] Hybrid pump reconnect

- pumps/elasticsearch.go
- pumps/kafka.go
Adding configuration for auth mechanism in Kafka and ElasticSearch:
-  basic auth (plain and scram) for Kafka
-  basic auth (username and password) and API Key auth (api_key and api_key_id) for ElasticSearch.
**ElasticSearch:**
Basic auth configuration:
The fields **auth_basic_username** and **auth_basic_password** are added into ES configuration. Those fields are going to be send in the Authorization header as `username:password` encoded in base64. 
Example config:
```
"elasticsearch": {
"type": "elasticsearch",
"meta": {
"index_name": "tyk_analytics",
"elasticsearch_url": "https://elastichost:9243",
"enable_sniffing": false,
"document_type": "tyk_analytics",
"rolling_index": false,
"extended_stats": false,
"version": "6",
"auth_basic_username":"elastic",
"auth_basic_password":"password" …
```
> [TN-4] [TN-3] Auth for Kafka and ES

- analytics/aggregate.go
- pumps/mongo_aggregate.go
Added `ignore_aggregations` in mongo aggregate pump conf to drop aggregations.
Values can be: "APIID","Errors","Versions","APIKeys","OauthIDs","Geo","Tags","Endpoints","KeyEndpoint","OauthEndpoint","ApiEndpoint"
This can be used to decrease the size of the aggregated document in case it takes too long to modify it.
https://tyktech.atlassian.net/browse/TT-696
https://tyktech.atlassian.net/browse/TT-696
1- Create an API with Auth token and detailed recording.
2- Configure pump with mongo-aggregate
3- Do some requests.
4- Check in mongo everything is aggregated.
5- Add "ignore_aggregations":["APIKeys"] to mongo-aggregate configuration.
6- Do more requests.
7- Check in mongo if the apikey aggregation was dropped
8- Check in the dashboard that activity per API Key is not increasing.
*Note*: …
> [TT-696] Ignore aggregations

- README.md
Adding docs for the timeout config option.
We don't have any documentation for pump timeouts.
> Docs for pumps timeout

- pumps/mongo.go
Changing the blurring of mongo logs to ` ***:***` for making them the same as our other blurred logs (ES for example)
> [TT-556]Replacing mongo blurring logs for ***

- go.mod
- go.sum
Logzio can't work with HTTP PROXY env variables.
It was fixed some time ago, so re-vendoring https://github.com/logzio/logzio-go/pull/4
> [TT-1189] Fix logzio HTTP PROXY proxy (re-vendor to latest master)

- main.go
Removed the default value of purge_chunk since it was causing problems in the Redis Lrange and it was not necessary.
Also, it caused problems to fetch 1 record from the Redis.
https://tyktech.atlassian.net/browse/TT-1335
https://tyktech.atlassian.net/browse/TT-1335
> [TT-1335] Removing default of chunk size

- pumps/prometheus.go
The prometheus pump counter for code, key combination is never incremented. The value therefor is always 0. 
By not incrementing the counter the usefulness of the metric becomes very little. We now only know a code occurred for a key in a given timeframe, not the quantity of which it did. 
> Increment prometheus keystatus counter

- README.md
- go.mod
- go.sum
- pumps/moesif.go
Add: EventQueueSize, BatchSize, and TimerWakeUpSeconds config option
Add: Support to fetch userId from authorization header
Bump moesifapi-go dependency to version v1.0.6
Setuped Tyk gateway locally, make the moesif pump, build the tyk-pump locally and test moesif pump changes by making api calls via tyk gateway which are captured by Moesif.
> Add: EventQueueSize, BatchSize, and TimerWakeUpSeconds config option

- pumps/kafka.go
Removing kafka default tls when `use_ssl` is false
Removing kafka default tls when `use_ssl` is false
https://tyktech.atlassian.net/browse/TT-1472
https://tyktech.atlassian.net/browse/TT-1472
following instructions in : https://tyktech.atlassian.net/browse/TT-1472
> [TT-1472]  Kafka no ssl bugfix

- README.md
- pumps/splunk.go
The purpose of this pull request is to extend the Tyk Splunk Pump with new functionality. This new functionality is related to the analytics data that is being sent to Splunk.
With the changes in this pull request, now we will be able to easily configure which Tyk analytic fields to be sent to Splunk.
Also, the API key obfuscation has been improved so you can now set how long the partially shown API key be.
[#12059](https://support.tyk.io/hc/en-gb/requests/12059)
Currently, each analytics record has around 30 items that can be passed to any data collector. But the Splunk Pump is sending only half of them. As a result, the received events lack information and are not optimal for troubleshooting.
The suggested feature has been tested in a real and active environment in our company. For more …
> Splunk Pump - Customizable analytics fields

- analytics/analytics.go
I've implemented the GetFieldNames and GetLineValues without reflection by simply including the details from the structures.
This is related to a customer support ticket 
https://support.tyk.io/hc/en-gb/requests/11978
GetFieldNames and GetLineValues were first written when AnalyticsRecord a very simple structure. As it's grown they have not been updated to deal with it. As a result the CSV output couldn't handle boolean values or the values stored in the sub-structures within AnalyticsRecord 
I've only tested it in my own docker environment. My interest was to scratch an itch and enjoy some recreational coding.
It's worked just fine though
I've tested calling APIs and reading the CSV output. My test setup doesn't populate the GeoData struct so it might be an idea to make sure that bit …
> [TT-2183] Create CSV from AnalyticsRecord without using reflectin

- config.go
- config_test.go
- main.go
- pumps/common.go
- pumps/csv.go
- pumps/dogstatsd.go
- pumps/dummy.go
- pumps/elasticsearch.go
- pumps/graylog.go
- pumps/hybrid.go
- pumps/influx.go
- pumps/kafka.go
- pumps/logzio.go
- pumps/moesif.go
- pumps/mongo.go
- pumps/mongo_aggregate.go
- pumps/mongo_selective.go
- pumps/prometheus.go
- pumps/pump.go
- pumps/segment.go
- pumps/splunk.go
- pumps/statsd.go
- pumps/syslog.go
Adding each pump to pumps slice with append to avoid having nil pump when init fails.
Adding a better message for Splunk pump when `ssl_insecure_skip_verify` is `false` but no key/cert is specified.
https://tyktech.atlassian.net/browse/TT-2151
https://tyktech.atlassian.net/browse/TT-2151
https://tyktech.atlassian.net/browse/TT-2151
> [TT-2151] Bugfix splunk pump panic

- README.md
- pumps/graylog.go
At the moment it is missing essential field. 
https://tyktech.atlassian.net/browse/TT-1809
It is supported by rest of the pumps
Not yet tested
> [TT-1809] Add support for IP address to Graylog pump

- analytics/aggregate.go
- pumps/sql.go
- pumps/sql_aggregate_test.go
- pumps/sql_test.go
Changing the SQL pumps connection config from `meta.dsn` to `meta.connection_string` to match dashboard configuration.
https://tyktech.atlassian.net/browse/TT-2571
https://tyktech.atlassian.net/browse/TT-2571
Modified the tests, all run 👌 .
> [TT-2571] Change SQL connection config option

- pumps/mongo.go
Fixing uptime pump environment vars backwards compatibility issues.
Now, uptime pump checks for `PMP_MONGO_` env vars if there was nothing set on its config URL ( `TYK_PMP_UPTIMECONFIG_MONGOURL` is used as env var for that).
https://tyktech.atlassian.net/browse/TT-2640
https://tyktech.atlassian.net/browse/TT-2640 
Backwards compatibility between 1.2.0 and 1.3.0.
https://tyktech.atlassian.net/browse/TT-2640
> [TT-2640] Bugfix uptime pump env vars 

- pumps/sql.go
- pumps/sql_test.go
This PR changes the way we wrote data in `sql pump` in order to support multiple days when `table_sharding` is `true`.
Also, refactored `sql pump` tests a little bit for better readability and to make them easier to extend.
Unit tests
> new sharding mode in SQL pump + refactoring SQL tests

- analytics/analytics.go
- analytics/uptime_data.go
- config.go
- main.go
- pumps/pump.go
- pumps/sql.go
- pumps/sql_test.go
Adding uptime SQL pump.
Now, you can configure a `uptime_type` in the `uptime_pump_config`, and depending on that, you can set the configuration fields. By default, the `uptime_type` is `mongo`. For SQL Uptime pumps, the `uptime_type` is `sql`.
In order to set uptime SQL pump:
```
"uptime_pump_config": {
"uptime_type":"sql",
"type":"sqlite",
"connection_string":"/Users/tomuz/test.db",
"table_sharding":false,
},
```
The uptime SQL Pump stores the data in an aggregated way, similar to `sql_aggregate`. It supports `table_sharding` and by default, the **aggregations are per hour**.
https://tyktech.atlassian.net/browse/TT-2117
https://tyktech.atlassian.net/browse/TT-2117
Added unit tests and tested manually with `sqlite` configured in the dashboard analytics storage.
fork, don't request your …
> [TT-2117] Feature/uptime sql

- analytics/aggregate.go
- pumps/sql_aggregate.go
- pumps/sql_aggregate_test.go
This PR solves the edge case for SQL Aggregation when the data contains multiple dates (more than 2 days).
Also, it contains a little refactor of SQL aggregate tests and assigns the db write to a new variable to db miss utilization.
https://tyktech.atlassian.net/browse/TT-2783
https://tyktech.atlassian.net/browse/TT-2783
Unit tests + ran pump in demo mode.
> [TT-2837] Bugfix - SQL Aggregate table sharding edge cases

- analytics/aggregate.go
- pumps/sql.go
- pumps/sql_aggregate.go
- pumps/sql_aggregate_test.go
SQL Aggregate now aggregate the same records per hour. It uses the following index to identify the records: day-month-year-hour + OrgID + dimension+ dimension_value.
https://tyktech.atlassian.net/browse/TT-2673
https://tyktech.atlassian.net/browse/TT-2673
Added unit tests
> [TT-2673] SQLAggregate Pump - aggregations per hour 

- analytics/aggregate.go
- analytics/uptime_data.go
- pumps/sql_aggregate_test.go
Change the SQL ON CONFLICT AVG formula for `request_time`, `upstream_latency` and `latency` to avoid precision loss. Now it's more simple and we just do a `AVG = (oldTotal + newTotal ) / (oldHits + newHits)`.
Also included `total_latency` to the ON CONFLICT clauses since it was missing.
This apply for `sql_aggregate` and uptime pump
https://tyktech.atlassian.net/browse/TT-2900
https://tyktech.atlassian.net/browse/TT-2900
Added unit tests for sql_aggregate.
> [TT-2900] Bugfix/SQL total latency + AVG precision loss

- analytics/aggregate.go
- analytics/uptime_data.go
- pumps/sql_aggregate_test.go
Added on conflict clause to update `last_access` column in SQL aggregate and Uptime SQL pumps.
https://tyktech.atlassian.net/browse/TT-2898
https://tyktech.atlassian.net/browse/TT-2898
Added unit test for aggregated SQL.
> [TT-2898] Bugfix/sql last access

- analytics/analytics.go
This PR helps moving country to be type so we can use it when building proper tests on analytics side
> TT-2958 - fixed GEO types

- analytics/aggregate.go
- analytics/uptime_data.go
- pumps/sql_aggregate_test.go
Adding `last_time` value for Aggregate `total` counter / dimension.
Also changing last_time format since `sqlite` have problems with normal `time.Time` format and `RFC3339` format changes.
https://tyktech.atlassian.net/browse/TT-2898
https://tyktech.atlassian.net/browse/TT-2898
Added unit test for SQL Aggregate.
> [TT-2898]  last_time value for total counters

- pumps/elasticsearch.go
When bulk operations are enabled, then we should print the number of records purged only when we commit to ElasticSearch and not during the appending process. In order to do so, I used the `BulkAfterFunc` function that is triggered when we commit the bulk to ES even if its successful or a failure.
https://tyktech.atlassian.net/browse/TT-2925
Give solution to https://tyktech.atlassian.net/browse/TT-2925
Using ES6 with the next configurations/situations:
- **Situation 1:**
Bulk size not set, so it should fallback to 1000.
```
"elasticsearch": {
"type": "elasticsearch",
"meta": {
"index_name": "tyk_analytics",
"elasticsearch_url": "http://localhost:9200",
"enable_sniffing": false,
"document_type": "tyk_analytics",
"rolling_index": false,
"extended_stats": false,
"version": "6", …
```
> TT-2925 improve es logs when bulk enabled

- README.md
> SQL, SQL Aggregate and SQL Uptime pumps docs

- pumps/prometheus.go
This PR adds validation for context in each for loop cycle in Prometheus pump. If the context is canceled, it writes how many records were lost in a Warn message.
https://tyktech.atlassian.net/browse/TT-3178
https://tyktech.atlassian.net/browse/TT-3178
**TBD**
> TT-3178 Prometheus pump timeout

- pumps/elasticsearch.go
- Removing unnecessary DEFAULT_BULK_SIZE
- Adding the bulk print only when `disble_bulk` is false.
- Adding flushing log when ES pump shutdown.
https://tyktech.atlassian.net/browse/TT-2925
https://tyktech.atlassian.net/browse/TT-2925
>  TT-2925 bulk ES logs

- analytics/analytics_filters.go
- config.go
- pumps/csv.go
- pumps/dogstatsd.go
- pumps/elasticsearch.go
- pumps/graylog.go
- pumps/influx.go
- pumps/kafka.go
- pumps/logzio.go
- pumps/moesif.go
- pumps/mongo.go
- pumps/mongo_aggregate.go
- pumps/mongo_selective.go
- pumps/prometheus.go
- pumps/segment.go
- pumps/splunk.go
- pumps/sql.go
- pumps/sql_aggregate.go
- pumps/statsd.go
- pumps/stdout.go
- pumps/syslog.go
- storage/redis.go
Added inline documentation inside the config files for the pump, pumps, redis, and analytics.
Documenting in line and for the Tyk docs site.
> Add documentation to pump configs for auto generating tyk-docs

- pumps/influx.go
Fixing a missing } and Tags var that was deleted on mistake on docs addition
> Fixing influx typo 

- pumps/influx.go
- pumps/mongo_aggregate.go
- pumps/sql_aggregate.go
Decoupling aggregated writing from `WriteData` method in SQL and Mongo aggregate pumps in order to make it possible to embed them in MDCB.
> Decoupling aggregated writing

- README.md
- pumps/influx2.go
Adding readme docs for Influx2 Pump and some missing inline comments
> Adding docs for influxdb 2

- main.go
- pumps/version.go
- version.go
Add mssing version.go in order to normalice design as done in tyk,dashboard, etc
> add missing version.go

- pumps/moesif.go
Refactor: Moesif Pump converts an entity (user/company) config name to lowercase when fetching an entity (user/company) from the headers
Earlier/Previous Behavior - 
Moesif pump was not converting an entity (user/company) config name to lowercase but only converting request/response headers to the lowercase which resulted into an entity (user/company) config is not getting fetched when reading from the headers.
This PR changes - 
Moesif Pump converts an entity (user/company) config name to lowercase when fetching an entity (user/company) from the headers. Both headers and config name would be in the lowercase, so will be fetched and logged in Moesif.
Setuped Tyk gateway locally, make the moesif pump, build the tyk-pump locally and test moesif pump changes by making api calls via tyk …
> TT-4635 Refactor: Moesif pump converts entity config name to lowercase

- .github/workflows/sync-automation.yml
.g/w/api-tests.yml does not exist for this this repo.
> minor: remove unnecessary file

- README.md
Adds some docs for https://github.com/TykTechnologies/tyk-pump/pull/419#issuecomment-1049351609
> Add auth instructions for Timestream pump

- ci/install/data/pumpsql.template.conf
- ci/install/setup.sh
Adding `-sqlite` and `-postgres` configuration option along with a new template for SQL pumps.
> [TT-4713] Updating setup.sh with SQL support

- config.go
- go.mod
- go.sum
- main.go
- server/server.go
This PR adds `enable_http_profiler` configuration option for Tyk pump, which will expose profiling endpoints in the same way as the Tyk Gateway https://tyk.io/docs/troubleshooting/tyk-gateway/profiling/
It also changes the routing lib to mux in order to be more cohesive with Tyk Gateway code.
> Enabling HTTP profiling 

- pumps/elasticsearch.go
Updated error msg when a non valid version of ES is provided. It should say as well that tyk-pump supports v7
https://tyktech.atlassian.net/browse/TT-3783
Be informative and consistent
- Create a config file with an ES pump
- Set the version to be a value that is not supported. Eg: 10
- Execute tyk-pump...you should receive an error msg and ES 7 should appear in the error msg.
> TT-3783 update error msg when a non valid elasticSearch version is provided

- pumps/moesif.go
This PR adds a Shutdown function to the Moesif pump in order to Flush all the queued records on tyk pump shutdown. It will only happen when  `enable_bulk` is set to true.
https://tyktech.atlassian.net/browse/TT-3734
https://tyktech.atlassian.net/browse/TT-3734
- Setup a Moesif pump with enable_bulk true and bulk configuration:
```
"enable_bulk":true,
"bulk_config":{
"event_queue_size":1000,
"batch_size":50,
"timer_wake_up_seconds":2
}
```
- Run pump, send some request ( less than batch_size).
- You should not see anything in the moesif dashboard.
- Shutdown pump
- You should see a `Flushing bulked records` log and you should see now the records in the moesif dashboard.
> TT-3734 Moesif pump shutdown

- analytics/aggregate.go
- analytics/aggregate_test.go
now we sanitize the tags from using "."
https://tyktech.atlassian.net/browse/TT-1337
Sanitize properly the tags
- Added unit tests
- Test the same as https://tyktech.atlassian.net/browse/TT-3072
> TT-1337 sanitize dot from tags

- analytics/aggregate.go
When the tag is sanitised, do not use the old one and start using the cleaned one
- https://tyktech.atlassian.net/browse/TT-1337
Give solution to https://tyktech.atlassian.net/browse/TT-1337
- Same as https://tyktech.atlassian.net/browse/TT-3072 but adding dots in the tags
> TT-1337 use sanitized tag and not original tag

- .github/dependabot.yml
Updated the dependabot file so it looks for updates in the gomod file. It will do so every monday of every week and will assign the pull requests to the platform squad
https://tyktech.atlassian.net/browse/TT-5749
Keep dependencies updated
----
> TT-5749 updated the dependabot file to check gomod dependencies

- analytics/aggregate.go
- go.mod
- go.sum
- logger/init.go
- logger/init_test.go
- main.go
- pumps/common.go
- pumps/elasticsearch.go
- pumps/kafka.go
- pumps/moesif.go
- pumps/mongo.go
- pumps/mongo_aggregate.go
- pumps/prometheus.go
- pumps/pump.go
- pumps/stdout.go
- server/server.go
- storage/redis.go
This PR adapts Tyk Pump to use the same logging strategy as [Tyk Gateway](https://github.com/TykTechnologies/tyk/blob/5c96cd09ee25b401ac35fa50dca2a39419ff2b77/log/log.go#L49). 
Basically, it drops the `tyktechnologies/logrus` dependency and starts using `sirupsen/logrus`, and stops forcing colors into logs.
It also adds `SetLogLevel` to common pump to be able to set the logger level in individual pumps- this's especially useful when exporting pump code.
https://tyktech.atlassian.net/browse/TT-6152
> TT-6152 Logger normalization

- README.md
- pumps/prometheus.go
- pumps/prometheus_test.go
Key alias is now an available field to populate in custom metrics for Prometheus.
https://tyktech.atlassian.net/browse/TT-6127 
Client requested functionality.
Running both the Tyk Pro Docker Demo and Prometheus locally from my machine, I configured by my tyk-pump instance (running via compiled binary) to utilize custom metrics for Prometheus by adding the following configuration block to the pumps section of my pump.conf.
`"prometheus": {
"type": "prometheus",
"meta": {
"listen_address": "localhost:9999",
"path": "/metrics",
"custom_metrics":[
{
"name":"tyk_custom_http_status_per_api_name",
"description":"This is a custom counter",
"metric_type":"counter",
"labels":["response_code","api_name", "alias"]
}
]
}
}`
I created an API that required an Authorization Token.  I then proceeded to …
> Added key alias to list of fields available to Prometheus Pump (TT-6127)

- main_test.go
Refactor flaky TestTrimData test 
> Refactoring and fixing flaky TestTrimData test

- .github/workflows/ci-test.yml
- pumps/sql_aggregate_test.go
Refactor TestSQLAggregateWriteDataValues to avoid flaky tests
> Flaky TestSQLAggregateWriteDataValues

- pumps/version.go
> Bump version to v1.7

- pumps/mgo_helper_test.go
- pumps/mongo_selective.go
- pumps/mongo_selective_test.go
sizeBytes formula is miscalculated in Mongo Selective Pump. It is calculating the number of bytes of the raw request twice.  It should be the number of bytes of raw request + the number of bytes of raw response + 1kb for metadata (avg) size.
https://tyktech.atlassian.net/jira/software/c/projects/TT/boards/42?modal=detail&selectedIssue=TT-6550
Running current function tests
> TT-6550 | Document size is mis-calculated in Mongo Selective Pump

- analytics/analytics.go
Ignored the ApiSchema column in the migraion process, the issue with gorm is that it was throwing:
```
ERROR: syntax error at or near ")" (SQLSTATE 42601)
[4.724ms] [rows:0] CREATE TABLE "tyk_analytics" ("method" text,"host" text,"path" text,"rawpath" text,"contentlength" bigint,"useragent" text,"day" bigint,"month" bigint,"year" bigint,"hour" bigint,"responsecode" bigint,"apikey" text,"timestamp" timestamptz,"apiversion" text,"api_name" text,"apiid" text,"orgid" text,"oauthid" text,"requesttime" bigint,"rawrequest" text,"rawresponse" text,"ipaddress" text,"geo_country_iso_code" text,"geo_city_geoname_id" bigint,"geo_city_names" text,"geo_location_latitude" decimal,"geo_location_longitude" decimal,"geo_location_time_zone" text,"network_open_connections" bigint,"network_closed_connections" …
```
> ignore the field ApiSchema in SQL

- pumps/prometheus.go
Adding `_META` postfix to default prometheus env, like all other pumps.
https://tyktech.atlassian.net/browse/TT-6890
> TT-6890 Prometheus default env var postfix

- analytics/graph_record.go
- analytics/graph_record_test.go
- pumps/graph_mongo.go
- pumps/graph_mongo_test.go
fix edge case where the query is to an unresolved subgraph schema
[TT-6012](https://tyktech.atlassian.net/browse/TT-6012)
> [TT-6012] fix edge case where the query is to an unresolved subgraph schema

- pumps/internal/certs/certs.go
- pumps/internal/certs/certs_test.go
- pumps/internal/mgo/mgo.go
- pumps/mongo/helpers.go
- pumps/mongo/helpers_test.go
- pumps/mongo/mongo.go
- pumps/mongo/mongo_test.go
- pumps/mongo/uptime.go
- pumps/mongo/uptime_test.go
- pumps/mongo_aggregate.go
This PR increase the test coverage of mongo pump to `91.8%`
Coverage per file in mongo pkg:
- `helpers.go`: 96.4%
- `mongo.go`: 89.5%
- `mongo_conf.go`: 100%
- `uptime.go`: 100%
> Mongo Pump test coverage

- pumps/mongo.go
- pumps/mongo_test.go
This PR changes the current mongo blur URL regex to a more flex one to capture more edge scenarios.
It also adds tests around this.
https://tyktech.atlassian.net/browse/TT-6278
https://tyktech.atlassian.net/browse/TT-6278
> TT-6278  Mongo blur URL

- config.go
Changing the wording and the format/example to a more generic one since this configuration applies to all pumps.
https://tyktech.atlassian.net/browse/TT-6834
> TT-6834 Timeout documentation

- README.md
- analytics/analytics.go
- analytics/analytics_test.go
- config.go
- main.go
- main_test.go
- pumps/common.go
- pumps/pump.go
We are allowing users to ignore analytics record fields on their pumps. They can set this with any JSON tag of the [analytic record struct](https://github.com/TykTechnologies/tyk-pump/blob/master/analytics/analytics.go#L30) to ignore that field.
https://tyktech.atlassian.net/jira/software/c/projects/TT/boards/42?modal=detail&selectedIssue=TT-5429
It allows users to ignore fields that they don't really need.
Unit tests were created and it was also tested with Pump Demo Mode and Mongo Pump.
> [TT-5429] Tyk Pump Ignore Fields 

- go.mod
- go.sum
Updated version of TykTechnologies/gorm
https://tyktech.atlassian.net/browse/TT-7107
Fix https://tyktech.atlassian.net/browse/TT-7107
- Ran pumps with:
```
"pumps":{
"sql": {
"name": "sql",
"type":"sql",
"meta": {
"type": "postgres",
"connection_string": "host=localhost port=5432 user=admin dbname=raava password=secr3t sslmode=disable",
"table_sharding": false,
"batch_size": 1000,
"track_all_paths" : false,
"log_level":"debug"
}
},
"sql_aggregate":{
"name":"sql_aggregate",
"type":"sql_aggregate",
"meta":{
"type":"postgres",
"connection_string":"host=localhost port=5432 user=admin dbname=raava password=secr3t sslmode=disable",
"table_sharding":false,
"batch_size":1000,
"track_all_paths":false,
"log_level":"debug"
}
}
},
```
*your branch* off *our latest …
> TT-7107 updted version of TykTechnologies/gorm

- analytics/demo/demo.go
This is an annex of this PR https://github.com/TykTechnologies/tyk-pump/pull/513
https://tyktech.atlassian.net/browse/TT-5426?atlOrigin=eyJpIjoiYTU4ZGI1ZWNhZTE2NGE5YWJkZmE4ZmMxMTQ3ZDljN2EiLCJwIjoiaiJ9
> [TT-5426] Updating timestamp of every record in Demo Mode

- analytics/demo/demo.go
The timestamp is now using UTC timestamp by default, instead of the user's GMT.
https://tyktech.atlassian.net/browse/TT-5426?atlOrigin=eyJpIjoiZGYxOTQ1MjEyMDg2NDliYzkxMjRiYzkxYWYwZTliZmYiLCJwIjoiaiJ9
> TT-5426 - Demo Mode UTC timestamp by default

- pumps/timestream.go
Fixed a typo in timestream pump comments that makes the auto-generated docs write `Timesteram` instead of `Timestream`
> Fix typo in timestream pump docs

- pumps/version.go
Changing pump version from 1.7 to 1.7.0 for the release.
> TT-6543 using proper semantic for pump version

- .github/workflows/sync-automation.yml
Add an additional step in the sync automation workflow to enable automerge for the created PR.
TD-1348
> [TD-1348]: Enable automerge for sync automation PRs.

- README.md
Adding information about the changes made in https://github.com/TykTechnologies/tyk-pump/pull/486
https://tyktech.atlassian.net/browse/TT-506?atlOrigin=eyJpIjoiN2EwMWU5MGZlODVmNGUxN2I4ZTNmNzJmNWNlMWNhNTAiLCJwIjoiaiJ9
We need to describe what self-healing is and how it works. The documentation is being added in an external PR to not delay the PR that contains the code.
> TT-506/2 - Adding info about self-healing

- README.md
- analytics/demo/demo.go
- analytics/demo/demo_test.go
- main.go
Now users can choose between creating historical or future data when using Pump's Demo Mode. It will generate historical data by default.
https://tyktech.atlassian.net/browse/TT-7345?atlOrigin=eyJpIjoiZDBlN2I0YTlmYzc0NGIwZWFhNTI5YTMyMzg2NzAyODUiLCJwIjoiaiJ9
It allows users to create more realistic data. Historical data makes a lot more sense than future data, that's the reason of the change.
Unit tests + executing demo mode using Mongo Pump
> [TT-7345] Adding the possibility to create historical and future data in Pump's Demo Mode

- .github/workflows/ci-test.yml
- .github/workflows/release.yml
- .github/workflows/sync-automation.yml
> Deprecate set-output directive

- README.md
- analytics/graph_record.go
- analytics/graph_record_test.go
- pumps/graph_sql.go
- pumps/graph_sql_test.go
- pumps/init.go
- pumps/sql.go
This PR adds the Graph SQL pump, a pump that parses graphql records and saves it to SQL storage that will be used by the user and the dashboard for displaying analytics. Link to the story [here](https://tyktech.atlassian.net/browse/TT-7482) for more details
[TT-7482](https://tyktech.atlassian.net/browse/TT-7482)
[TT-7482]: https://tyktech.atlassian.net/browse/TT-7482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TT-7482] feat: implement graph sql pump

- logger/init.go
- logger/init_test.go
I've created a unit test for GetLogger() function. I've also deleted some unnecessary lines of code. Whenever TYK_LOGLEVEL has an invalid value (empty or a not valid string), the log level will be set as "info". That's why we don't need to add an "info" case in the switch sentence, we can just keep it as default.
**Before:**
**After:**
> Increasing test coverage of logger package

- .github/workflows/pac.yml
- .gitignore
- ci/repo-policy/main.tf
- ci/repo-policy/modules/github-repos/repo.tf
- ci/repo-policy/modules/github-repos/variables.tf
Adding terraform files for release branch management
> TD-1462/add-gpac

- analytics/aggregate.go
- analytics/aggregate_test.go
- pumps/graph_sql_aggregate.go
- pumps/graph_sql_aggregate_test.go
- pumps/hybrid.go
- pumps/init.go
- pumps/mongo_aggregate.go
- pumps/sql_aggregate.go
This PR implements the graphql specific SQL aggregate pump, for reading and parsing graphql requests.
[TT-7820](https://tyktech.atlassian.net/browse/TT-7820)
[TT-7820]: https://tyktech.atlassian.net/browse/TT-7820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TT-7820]Feat: sql aggregate pump

- .github/workflows/pac.yml
- ci/repo-policy/main.tf
- ci/repo-policy/modules/github-repos/repo.tf
Update backend to terraform cloud
> Change tf backend to cloud

- pumps/stdout.go
https://tyktech.atlassian.net/browse/TT-7539
https://tyktech.atlassian.net/browse/TT-7539
> TT-7539 Adding time to stdout pump

- analytics/aggregate.go
- analytics/graph_record.go
- analytics/graph_record_test.go
- pumps/graph_mongo.go
- pumps/graph_sql.go
- pumps/graph_sql_aggregate.go
- pumps/graph_sql_aggregate_test.go
This PR fixes the issue with the aggregate pump sharding and the error handling specified in the ticket
[TT-7820](https://tyktech.atlassian.net/browse/TT-7820)
[TT-7820]: https://tyktech.atlassian.net/browse/TT-7820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TT-7820] fix: Fix aggregate graph pump sharding and errors

- go.mod
- go.sum
https://tyktech.atlassian.net/browse/TT-8277
> Update murmur3 to latest

- README.md
Adding documentation about both tickets for Pump 1.8 Release
https://tyktech.atlassian.net/browse/TT-7216
https://tyktech.atlassian.net/browse/TT-8229
> Adding TT-7216 and TT-8229 to readme

- README.md
adding TT-7216 and TT-8229 to readme (#609)
> Merging to release-1.8: adding TT-7216 and TT-8229 to readme (#609)

- README.md
- pumps/influx2.go
- pumps/mongo.go
- pumps/mongo_aggregate.go
- pumps/mongo_aggregate_test.go
- pumps/mongo_selective.go
- pumps/mongo_selective_test.go
- pumps/mongo_test.go
Changing conf 'driver_type' to 'driver'
I'm also setting mongo-go as the default driver for Mongo Pumps
> Changing conf 'driver_type' to 'driver'

- README.md
- pumps/influx2.go
- pumps/mongo.go
- pumps/mongo_aggregate.go
- pumps/mongo_aggregate_test.go
- pumps/mongo_selective.go
- pumps/mongo_selective_test.go
- pumps/mongo_test.go
Changing conf 'driver_type' to 'driver' (#618)
* changing conf 'driver_type' to 'driver'
* updating readme
> Merging to release-1.8: Changing conf 'driver_type' to 'driver' (#618)

- pumps/mongo.go
Updating MongoDriverType comment
> Updating MongoDriverType comment

- pumps/mongo.go
updating MongoDriverType comment (#622)
> Merging to release-1.8: updating MongoDriverType comment (#622)

- pumps/mongo.go
- pumps/mongo_aggregate.go
- pumps/mongo_aggregate_test.go
- pumps/mongo_selective.go
- pumps/mongo_selective_test.go
- pumps/mongo_test.go
Changed the default mongo driver to mgo
https://tyktech.atlassian.net/browse/TT-8905
Unit tests
> TT-8905 changed the default mongo driver to mgo

- README.md
- go.mod
- go.sum
- pumps/mongo.go
- pumps/mongo_aggregate.go
- pumps/mongo_selective.go
Updating Pump with the fix from this PR: https://github.com/TykTechnologies/storage/pull/72
https://tyktech.atlassian.net/jira/software/c/projects/TT/boards/42?modal=detail&selectedIssue=TT-8873
> [TT-8873] Importing Storage v1.0.3 + Adding Direct Connection

- README.md
- go.mod
- go.sum
- pumps/mongo.go
- pumps/mongo_aggregate.go
- pumps/mongo_selective.go
Adding Direct Connection (#634)
> Merging to release-1.8: Adding Direct Connection (#634)

- pumps/prometheus.go
- pumps/prometheus_test.go
https://github.com/TykTechnologies/tyk-pump/pull/603 port
https://tyktech.atlassian.net/browse/TT-8761
https://tyktech.atlassian.net/browse/TT-8761
> TT-876 Fix/prometheus cardinality

- pumps/mongo.go
Rolled back a behaviour where the mongo pump ignores graph records being sent to it, this behaviour is being shelved for future implementations.
[TT-8884](https://tyktech.atlassian.net/browse/TT-8884)
[TT-8884]: https://tyktech.atlassian.net/browse/TT-8884?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TT-8884] fix: include grap records in mongo pump

- go.mod
- go.sum
Updating to storage v1.0.4 (#639)
> Merging to release-1.8: Updating to storage v1.0.4 (#639)

- pumps/mongo.go
fix: include grap records in mongo pump (#638)
> Merging to release-1.8: fix: include grap records in mongo pump (#638)

- pumps/hybrid.go
- pumps/hybrid_test.go
Default RPC pool size is set to 20 and because of the relatively heavy CPU and Memory footprint of the RPC connections in the MDCB model this can cause issues where either the gateways or MDCB fail on load cause by scaling events or component failure at MDCB side.
https://tyktech.atlassian.net/browse/TT-8942
https://tyktech.atlassian.net/browse/TT-8942
> TT-8942 Change default RPC pool size

- go.mod
- go.sum
https://tyktech.atlassian.net/browse/TT-8978?atlOrigin=eyJpIjoiN2ZlZTFkZDA5ZDZhNDg3M2I0N2RkMmVhMzZkZDA3OTkiLCJwIjoiaiJ9
> [TT-8978] Updating to storage v1.0.5

- go.mod
- go.sum
Updating to storage v1.0.5 (#646)
> Merging to release-1.8: Updating to storage v1.0.5 (#646)

- config.go
- config_test.go
If we have two or more pumps with the same name, but with different upper case / lower case characters (for example "mongo" and "Mongo"), Tyk-Pump takes them as different pumps with different configs, when they should be overwritten.
Now, all the pumps will be in upper case by default to avoid duplicates.
https://tyktech.atlassian.net/browse/TT-8999?atlOrigin=eyJpIjoiZjQ0MWIxZmZhMDllNDBjYWFiNDZmMDcyMDI3YTdkOWUiLCJwIjoiaiJ9
> [TT-8999] Overriding pumps with the same name

- pumps/pump.go
- pumps/pump_test.go
We have a map `AvailablePumps` that contains all the available pumps. The key of the map is the type written in lowercase (mongo, csv, prometheus, etc.) and the value is an instance of the pump itself:
https://github.com/TykTechnologies/tyk-pump/blob/54d0455505f8c864e9742ce608c9428560e6a101/pumps/init.go#L9
Since [this PR](https://github.com/TykTechnologies/tyk-pump/pull/648), we're defaulting all the pumps to uppercase in order to avoid repeated values and to allow users to override pumps through env vars. That's why we need to temporally make sure that the type is lowercase in order to get the struct from the AvailablePumps map.
https://tyktech.atlassian.net/browse/TT-8999?atlOrigin=eyJpIjoiMWQ2NDc5MmY3YzdjNGU5MDkzNWIwOWNmNDQzYmU5ZjgiLCJwIjoiaiJ9
Tested using Pump with and without env …
> [TT-8999] - Converting pump name to lower case when looking for it

- README.md
> Merging to release-1.8: Update README.md (#655)

- config.go
- pumps/mongo.go
Updating struct comments so we can roll out new docs with 1.8.1 release
> Updating struct comments

- config.go
Adding comment to 'meta' field (#668)
* Updating comments
* adding comments to 'name' and 'type'
* adding comment to Meta field
* changing IgnoreFields position
* fixing False syntax error
* fixing True syntax error
> Merging to release-1.8: Adding comment to 'meta' field (#668)

- .github/workflows/release.yml
pin point goreleaser version (#677)
> Merging to release-1.8: pin point goreleaser version (#677)

- pumps/mongo.go
- pumps/mongo_test.go
update regex to blur mongo credentials (#686)
> Merging to release-1.8: update regex to blur mongo credentials (#686)

- go.mod
- go.sum
[TT-9464] Updating storage to v1.0.8 (#698)
* Updating storage to v1.0.7
* go mod tidy
* Updating storage to v1.0.8
[TT-9464]: https://tyktech.atlassian.net/browse/TT-9464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Merging to release-1.8: [TT-9464] Updating storage to v1.0.8 (#698)

- analytics/graph_record.go
- pumps/graph_sql.go
There is currently a bug where the  graph SQL pump throws an error if ou try to run it with a different table name. It is due to gorm getting and using the same value as the "TableName()" for graph records, regardless of the value used `db.Table` when migrating. 
[TT-9855](https://tyktech.atlassian.net/browse/TT-9855)
[TT-9855]: https://tyktech.atlassian.net/browse/TT-9855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TT-9855]: fix index creation error on graph sql pump creation

- pumps/prometheus.go
- pumps/prometheus_test.go
TT-9873 Fix prometheus tracking path (#716)
* Fix prometheus tracking path
* suggested fixes
> Merging to release-1.8: TT-9873 Fix prometheus tracking path (#716)

- analytics/graph_record.go
- pumps/graph_sql.go
[TT-9855]: fix index creation error on graph sql pump creation (#715)
* fix index creation error
* fix ci
* fix lint
[TT-9855]: https://tyktech.atlassian.net/browse/TT-9855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Merging to release-1.8: [TT-9855]: fix index creation error on graph sql pump creation (#715)

- pumps/prometheus.go
Correcting the gramma of the comment of this field.
> Updating TrackAllPaths comment

- pumps/prometheus.go
updating TrackAllPaths comment (#722)
> Merging to release-1.8: updating TrackAllPaths comment (#722)

- .github/workflows/release.yml
- ci/tests/csvpump/docker-compose.yml
- ci/tests/csvpump/test.sh
- main.go
- pumps/version.go
These variables are set at build time. These changes help the releng templates use a standard build argument. See https://tyktech.slack.com/archives/C03PT641CF9/p1699582096160529
> [SYSE-294] Standardise build time variables

- go.mod
- go.sum
TT-11099 Upgrade storage v1.2.0 (#778)
* upgrade storage v1.2.0
* tidy
> Merging to release-1.9: TT-11099 Upgrade storage v1.2.0 (#778)

- pumps/graph_mongo.go
- pumps/graph_sql_aggregate.go
This PR fixes a bug that was noticed while making updates to the tyk-pump helm chart, where some Graphql pumps were not initiated with env values that did not use the default env value key.
> [TT-11070]:fix bug where some graphql pumps are not reading env properly

- main.go
Fixing a bug where Pump wasn't purging records because of a wrong KeyPrefix.
> Bugfix: Pump not purging records

- main.go
Removing pointer from AnalyticsStorageConfig variable (#786)
> Merging to release-1.9: Removing pointer from AnalyticsStorageConfig variable (#786)

- README.md
Fix typo in SQS Pump section (#788)
* Update README.md
* Update README.md
> Merging to release-1.9: Fix typo in SQS Pump section (#788)

- README.md
Quick update stating that mongo-go version is default from v1.9.0
> Update README.md to add mongo-go default from version v.1.9.0

- .github/workflows/ci-test.yml
separate lintern in ci from tests (#828)
> Merging to release-1.9: separate lintern in ci from tests (#828)

- analytics/analytics_filters.go
Update config.go where possible for inclusive naming project
> [DX-1345] Update config.go where possible for inclusive naming project

- .github/workflows/release.yml
> [SYSE-370 master] June template application

- pumps/hybrid.go
[DX-1437] Replace authorise with authorize in godoc comments (#840)
* replace authorise with authorize in godoc comments
* add organization
---------
Co-authored-by: Simon Pears <simon@tyk.io>
[DX-1437]: https://tyktech.atlassian.net/browse/DX-1437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Merging to release-1.10: [DX-1437] Replace authorise with authorize in godoc comments (#840)

- .github/workflows/ci-test.yml
- .github/workflows/linter.yaml
- .github/workflows/release.yml
- .golangci.yaml
- Dockerfile
- go.mod
In order to get rid of a reported CVE that's present in Go versions lower than v1.22.7, we need to update it.
Slack thread: https://tyktech.slack.com/archives/C029UHHJ03T/p1729772954993819
CVE link: https://scout.docker.com/vulnerabilities/id/CVE-2024-34158?s=golang&n=stdlib&t=golang&vr=%3C1.22.7&utm_source=desktop&utm_medium=ExternalLink
https://tyktech.atlassian.net/browse/TT-13428?atlOrigin=eyJpIjoiNzJhYzM3OTA5ZDRiNDM2Njg2MWZjMWE0OGMwMmQwYTkiLCJwIjoiaiJ9
https://tyktech.atlassian.net/browse/TT-13428?atlOrigin=eyJpIjoiNzJhYzM3OTA5ZDRiNDM2Njg2MWZjMWE0OGMwMmQwYTkiLCJwIjoiaiJ9
> [TT-13428] Upgrading Go to v1.22.7

- .github/workflows/ci-test.yml
- README.md
- ci/install/setup.sh
- config.go
- go.mod
- go.sum
- pumps/graph_sql_aggregate.go
- pumps/graph_sql_aggregate_test.go
- pumps/graph_sql_test.go
- pumps/sql.go
- pumps/sql_aggregate.go
- pumps/sql_aggregate_test.go
- pumps/sql_test.go
This PR removes SQLite as a supported SQL pump type across the project:
- Updated documentation to remove SQLite references
- Removed SQLite-related dependencies from go.mod and go.sum
- Updated test cases to use Postgres instead of SQLite
- Updated configuration documentation to clarify supported SQL pump types
- Removed SQLite-specific code in SQL pump implementations
https://tyktech.atlassian.net/browse/TT-13341
https://tyktech.atlassian.net/browse/TT-13341
> [TT-13341] Remove SQLite support from Tyk Pump

- pumps/version.go
> Bump version to 1.12.0

- .github/workflows/ci-test.yml
- .github/workflows/linter.yaml
- .github/workflows/release.yml
- .golangci.yaml
- Dockerfile
- go.mod
PR for: https://tyktech.atlassian.net/browse/TT-15025
> [TT-15025] Update Pump to Go 1.24
